[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
programs = "8MKSwpR9qs9zZj5bNUpzY5s8zijogrpB1PXDsBbziDVG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
