[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
programs = "2SeFqJPiM5MoTh3PdDBJn2jveCsYYk7GSMuABJ3zvpzc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
